AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python-sam-app

  Sample SAM Template for python-sam-app

Globals:
  Function:
    Timeout: 3

Resources:
  BmonsterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Bmonster:
          Type: Api
          Properties:
            Path: /bmonster
            Method: get

Outputs:
  BmonsterApi:
    Description: "API Gateway endpoint URL for Prod stage for b-monster function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/bmonster/"
  BmonsterFunction:
    Description: "b-monster Lambda Function ARN"
    Value: !GetAtt BmonsterFunction.Arn
  BmonsterFunctionIamRole:
    Description: "Implicit IAM Role created for b-monster function"
    Value: !GetAtt BmonsterFunctionRole.Arn
