AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python-sam-app

  Sample SAM Template for python-sam-app

Parameters:
  Env:
    Type: String
    Default: local
    AllowedValues:
      - local
      - develop
      - staging
      - production

Mappings:
  local:
    Aws:
      Region: ap-northeast-1
      DynamoDBHost: http://dynamodb-local:8000
      DynamoDBBillingMode: PAY_PER_REQUEST
  develop:
    Aws:
      Region: ap-northeast-1
      DynamoDBHost: ""
      DynamoDBBillingMode: PAY_PER_REQUEST

Globals:
  Function:
    Timeout: 3
    Runtime: python3.9
    Environment:
      Variables:
        ENV: !Ref Env
        REGION: !FindInMap [!Ref Env, Aws, Region]
        DYNAMODB_HOST: !FindInMap [!Ref Env, Aws, DynamoDBHost]
        BILLING_MODE: !FindInMap [!Ref Env, Aws, DynamoDBBillingMode]

Resources:
  BmonsterRequirementsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: requirements/
      CompatibleRuntimes:
        - python3.9
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.9

  BmonsterScrapingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.scraping.lambda_handler
      Layers:
        - !Ref BmonsterRequirementsLayer
      Timeout: 300
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: "cron(1 15 * * ? *)"

  BmonsterScheduleApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.schedule.lambda_handler
      Layers:
        - !Ref BmonsterRequirementsLayer
      Timeout: 30
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        Get:
          Type: Api
          Properties:
            Path: /bmonster/schedule
            Method: get

  BmonsterProgramApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.program.lambda_handler
      Layers:
        - !Ref BmonsterRequirementsLayer
      Timeout: 30
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        Get:
          Type: Api
          Properties:
            Path: /bmonster/program
            Method: get

  BmonsterProgramReviewApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.program_review.lambda_handler
      Layers:
        - !Ref BmonsterRequirementsLayer
      Timeout: 30
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        Get:
          Type: Api
          Properties:
            Path: /bmonster/programReview
            Method: get
        Post:
          Type: Api
          Properties:
            Path: /bmonster/programReview
            Method: post

Outputs:
  BmonsterApi:
    Description: "API Gateway endpoint URL for Prod stage for b-monster function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/bmonster/"
  BmonsterScrapingFunction:
    Description: "b-monster Lambda Function ARN"
    Value: !GetAtt BmonsterScrapingFunction.Arn
  BmonsterScrapingFunctionIamRole:
    Description: "Implicit IAM Role created for b-monster function"
    Value: !GetAtt BmonsterScrapingFunctionRole.Arn
  BmonsterScheduleApiFunction:
    Description: "b-monster Lambda Function ARN"
    Value: !GetAtt BmonsterScheduleApiFunction.Arn
  BmonsterScheduleApiFunctionIamRole:
    Description: "Implicit IAM Role created for b-monster function"
    Value: !GetAtt BmonsterScheduleApiFunctionRole.Arn
  BmonsterProgramApiFunction:
    Description: "b-monster Lambda Function ARN"
    Value: !GetAtt BmonsterProgramApiFunction.Arn
  BmonsterProgramApiFunctionIamRole:
    Description: "Implicit IAM Role created for b-monster function"
    Value: !GetAtt BmonsterProgramApiFunctionRole.Arn
  BmonsterProgramReviewApiFunction:
    Description: "b-monster Lambda Function ARN"
    Value: !GetAtt BmonsterProgramReviewApiFunction.Arn
  BmonsterProgramReviewApiFunctionIamRole:
    Description: "Implicit IAM Role created for b-monster function"
    Value: !GetAtt BmonsterProgramReviewApiFunctionRole.Arn
