AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python-sam-app

  Sample SAM Template for python-sam-app

Parameters:
  Env:
    Type: String
    Default: local
    AllowedValues:
      - local
      - develop
      - staging
      - production

Mappings:
  local:
    Aws:
      Region: ap-northeast-1
      DynamoDBHost: http://dynamodb-local:8000
      DynamoDBBillingMode: PAY_PER_REQUEST
  develop:
    Aws:
      Region: ap-northeast-1
      DynamoDBHost: ""
      DynamoDBBillingMode: PAY_PER_REQUEST

Globals:
  Function:
    Timeout: 3
    Runtime: python3.9
    Environment:
      Variables:
        ENV: !Ref Env
        REGION: !FindInMap [!Ref Env, Aws, Region]
        DYNAMODB_HOST: !FindInMap [!Ref Env, Aws, DynamoDBHost]
        BILLING_MODE: !FindInMap [!Ref Env, Aws, DynamoDBBillingMode]

Resources:
  BmonsterScrapingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.scraping.lambda_handler
      Timeout: 300
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: "cron(1 15 * * ? *)"

Outputs:
  BmonsterApi:
    Description: "API Gateway endpoint URL for Prod stage for b-monster function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/bmonster/"
  BmonsterScrapingFunction:
    Description: "b-monster Lambda Function ARN"
    Value: !GetAtt BmonsterScrapingFunction.Arn
  BmonsterScrapingFunctionIamRole:
    Description: "Implicit IAM Role created for b-monster function"
    Value: !GetAtt BmonsterScrapingFunctionRole.Arn
